baseURL = ""
DefaultContentLanguage = "de"
languageCode = "de-de"
title = "Ebook-Generator"
author = "Erhard Maria Klein"
copyright = "Copyright © 2020 Erhard Maria Klein, https://weitblick.org"

disableKinds = ["RSS", "robotsTXT", "404", "taxonomy", "section", "term", "sitemap"]

uglyurls = true
relativeURLs = true
disablePathToLower = true

[params]
  imgsize = "1200x q70" 
# imgsize = "800x png" # png works better with older ebook reader
  bookid = "" # if empty the unix timestamp is taken
# metadata of your ebook
  title = "HUGO Epub Theme"
  subtitle = "from weitblick.org" # (optional)
  description = "A simple HUGO theme for creating epub ebooks" # (optional)
  creator = "Klein, Erhard Maria" # format: lastname, firstname
  author = "Erhard Maria Klein" # format: firstname lastname
  publisher = "Weitblick Internetwerkstatt"
  audience = "teenagers, adults"
  subject = ['HUGO', 'Epub', 'Ebook'] # (optional)

[module]
replacements = 'github.com/MattVonVielen/hugo-epub -> ../..'
[[module.imports]]
path = 'github.com/MattVonVielen/hugo-epub'

[outputs]
_merge = 'shallow'
[permalinks]
_merge = 'shallow'
